### PR TITLE
Component conversion (Phase 1)

### PR DESCRIPTION
**Pull request by fogity**
This is the first phase of adding game component conversion to Strange Eons.
I tried to match the style and structure of the existing code, but I was a bit unsure about some of it.
Any improvement suggestions are welcome.

### Motivation

Strange Eons currently has a mechanism for upgrading old components when they are being read from disk. But this mechanism does not allow for splitting or merging component types. The intent of the conversion feature is to allow just that, and also allow manual conversion between features later on.

### Scope

Phase 1 focuses on the framework changes needed to perform the conversion and how the component code will interact with the feature. It also includes everything necessary to implement conversion on upgrade.
Phase 2 will cover allowing extensions to register supported conversions and the ability for users to manually trigger conversions.

### Overview

- Added hooks for compiled/DIY components to implement conversion logic
- Added hook/method for compiled/DIY components to request conversion when upgrading a component
- Added ConversionContext class which is used to store information needed during conversion
- Added ConversionUtilities class which provides methods to help with conversion
- Added convertGameComponent method to ResourceKit for performing the conversion itself
- Modified getGameComponentFromStream method in ResourceKit to perform conversion if requested by a component

### Example
Here is a Strange Eons project that contains some examples of the conversion feature:
[Conversion Showcase.zip](https://github.com/CGJennings/strange-eons/files/7434592/Conversion.Showcase.zip)

### CODE REVIEW

**Comment by CGJennings** [comment]
Thanks for your work on this!

This may look like a lot, but rest assured that on the whole it looks good!

## requireConversion

Is the idea that `requireConversion` would be called only from `onRead`, and if you want to start a conversion at another time you would use `ResourceKit.convertGameComponent` as the entry point? If so, call `checkPropertyLock()` at the start of `requireConversion`. Then it'll throw an exception if called when the component is not being either created or loaded.

I wonder if the name quite captures the intent. Maybe something like `convertToComponentType`?

## ConversionContext

Should `ConversionContext` should have a cancel method to keep the old component as is? E.g., you encounter an unexpected problem during conversion and you want to make sure users don't lose anything and will still have access to their content.

I see the potential for `Target`, but an enum may be too restrictive. As it can't be extended, the the plug-in developer is stuck with the values you provide (currently just one). You could let the developer set a user-specified object on the context so they can describe more complex situations (or even pass some parameters to the conversion code). It's an advanced use case, so I don't have a problem with it being harder to use correctly.

## ConversionUtilities

It would be more flexible for `ConversionUtilities` to have a method to copy a portrait from index `i` of the source component to index `j` of the destination component. Then the existing `copyPortraits` could be a convenience that adds the loop on top of that.

A `moveKeys` that would rename the keys as they are copied seems useful. E.g., `moveKeys(d, t, "OLD_KEY1", "NEW_KEY1", "OLD_KEY2", "NEW_KEY2", ...)`. In Java this looks wrong, but it's convenient for scripting.

Something like `copySettingsExcept("EXCLUDED1", ...)` may also be convenient, though it can be accomplished with, e.g., `copyKeys(Array.from(diy.settings).filter((key) => EXCLUDED_KEY_ARRAY.indexOf(String(key)) < 0))`.

## Is ConversionUtilities needed?

Perhaps I am missing something, but it seems like the static methods of `ConversionUtilities` could just be regular methods on `ConversionContext`. Then instead of 

```js
function onConvertFrom(diy, target, context)  {
  context.copyPortrait = true;
  ConversionUtilities.copyKeys(diy, target, "KEY1", "KEY2");
}
```

you could have

```js
function onConvertFrom(diy, target, context)  {
  context.copyPortraits();
  context.copyKeys("KEY1", "KEY2");
}
```

which is more consistent and doesn't require script writers to import a class. If you make the API fluent you could do, e.g., `context.copyPortraits().copyKeys(KEYS);` for simple cases.

If a `Portrait` is an instance of `DefaultPortrait`, you *should* be able to [transfer the image and source without creating a temporary file](http://se3docs.cgjennings.ca/assets/javadoc/ca/cgjennings/apps/arkham/component/DefaultPortrait.html#setImage(java.lang.String,java.awt.image.BufferedImage)). It would make conversion faster in most cases, but it isn't strictly necessary.

## DIYEditor

It looks like some stubs were added to `DIYEditor` that you didn't ultimately use. Are they needed? Even if the old component is open, it shouldn't be affected by the conversion. If you want to do an in-place conversion of an open file (from a tool plug-in for example), you could do something like

```java
final StrangeEonsEditor oldEditor = StrangeEons.getWindow().getActiveEditor();
GameComponent gc = oldEditor.getGameComponent();
if (gc != null) {
  // check old type and convert to new type
  gc = ...
}
final StrangeEonsEditor newEditor = gc.createDefaultEditor();
StrangeEons.getWindow().addEditor(newEditor);
((AbstractGameComponentEditor) oldEditor).setUnsavedChanges(false);
oldEditor.close();
```

## Handler interface

You should either add `onConvertFrom`/`onConvertTo` to the `Handler` interface, or use `ScriptMonkey.ambivalentCall` but not both. The `DIY.createHandler` method creates a proxy object that implements `Handler` using calls to the script. So in `DIY` all you have to do forward the call to the `Handler` object. (Have a look at what `DIY.paintFront` does.) This is why the code did not previously keep a reference to `ScriptMonkey`.

For this feature, it might actually be preferable to leave these functions *out* of the interface. Then you can avoid the awkwardness of having both `convertTo` and `onConvertTo` defined in `DIY` and just have something like:

```java
    @Override
    public void convertTo(GameComponent source, ConversionContext context) {
        if (monkey != null) {
            monkey.ambivalentCall("onConvertTo", diy, target, context);
        }
    }
```

Leaving these functions out of the `Handler` interface means conversion won't work with things like test instances, but those never call `onRead` anyway.

## Plug-in identity

This is more like useful information than thoughts about the PR specifically, but maybe it will spark something. I noticed that you incorporated an optional file name for error messages. I wanted to mention that plug-ins can be uniquely identified by a UUID. (It's the first part of the catalogue ID, the other part being a timestamp for versioning purposes.)

Now, the best time to use this might be before you even start the conversion process rather than as part of an error message. For example, given a plug-in UUID, you can look up if it is installed:

```js
const TALISMAN_ID = "eba51f9f-4016-4009-a452-c89f8801b899";
const TALISMAN_UUID = java.util.UUID.fromString(TALISMAN_ID);
const file = arkham.plugins.BundleInstaller.getBundleFileForUUID(TALISMAN_UUID);
const installed = file !== null;
```

Assuming a missing plug-in is in the catalog, you could even prompt users to install it:

```js
if (!installed) {
  const d = new arkham.plugins.catalog.CatalogDialog(Eons.window);
  d.setListingFilter(TALISMAN_ID);
  d.setPopupText("Install this, then start the conversion again.");
  d.setVisible(true);
  // abort conversion?
  return; 
}
```

**Comment by fogity** [comment]
Thank you for the thorough feedback! I have addressed the majority of your points, and made some additional changes to the conversion framework.

## Overview

* Renamed `requireConversion` and added the check as suggested
* Reworked `ConversionContext` and `ConversionUtilities`
* Removed the new methods from the `Handler` interface
* Added a prompt for installing missing plugin (if found in the catalog)

## ConversionTrigger
To trigger a conversion, I replaced  `ConversionContext` and the `Trigger` enum with `ConversionTrigger`. It is an interface with getters for values needed to identify the new component type (and extension) and has a `getCause` method to replace the enum. I made an abstract class and `UpgradeConversionTrigger` that is used for upgrade conversions. It should be easy for plug-ins to extend this part now.

## ConversionSession
Instead of splitting conversion code between three classes:

* `ResourceKit` to start a conversion
* `ConversionContext` to get info and handle auto-behavior
* `ConversionUtilities` to perfom common conversion tasks

I have consolidated everything into one class: `ConversionSession`. 
It has a static method for perfoming a conversion, which creates the new component and an instance of the session. The session is sent to both components and they use it to get all info and perform the conversion.
By your suggestions I added some more helper methods, made the API fluent, and added a `cancel` method.
I also removed the components as arguments to `convertFrom` and `convertTo`, to encourage using the session methods.

## Copying portrait images
I tried to use `setImage` to copy the images directly between the two portraits at first, but I just got errors. So I used the temporary file method instead.

## Example
I updated the examples, and added a couple more for the new methods:
[Conversion Showcase V2.zip](https://github.com/CGJennings/strange-eons/files/7449546/Conversion.Showcase.V2.zip)

**Comment by CGJennings** [comment]
Re: setting the image directly. I forgot that for compatibilty reasons the built-in portraits on `DIY`s don't use `DefaultPortait`, so it wouldn't help in most cases.

I made a few small changes to round things out:

1. The catalog message is now localizable.

2. The `rawId` string can now be a UUID (as before) or a full catalog ID. If a full ID is given, it will also take the *version* into account when deciding if you need to install something. You can play around with this from Quickscript with:

```js
const idToTest = 0; // CHANGE THIS
const ids = [
	// any version of AH, by UUID
	"7c299a1e-3ed6-49ea-9830-fc5c967764e9",
	// current version of SuperSystem, by cat ID
	"CATALOGUEID{31889e14-dfda-42d6-90f8-098838fc83a9:2015-2-24-19-23-25-605}",
	// older version of SuperSystem
	"CATALOGID{31889e14-dfda-42d6-90f8-098838fc83a9:2010-0-1-0-0-0-0}",
	// and a version from the far future
	"catalogid{31889e14-dfda-42d6-90f8-098838fc83a9:3000-0-1-0-0-0-0}",
	// random UUID that isn't available
	java.util.UUID.randomUUID().toString()
];
const trigger = new JavaAdapter(
	arkham.component.conversion.ConversionTrigger,
	{
		getCause: function() {
			return "testing";
		},
		getTargetClassName: function() {
			return "diy:talisman2/diy-token.js"
		},
		getRequiredExtensionName: function() {
			return "ZabbityBoo.seext";
		},
		getRequiredExtensionId: function() {
			return ids[idToTest];
		}
	}
);
const gc = new arkham.diy.DIY("talisman2/diy-token.js", "TAL_legacy", false);
arkham.component.conversion.ConversionSession.convertGameComponent(
	trigger, gc, true
);
```

3. If in interactive mode and the plug-in is not in the catalog, a message that describes the plug-in (and version) will be displayed instead of the catalog.

4. When showing the catalog dialog, it will now also select the required extension. The user need only choose **Download and Install**.

5. The interactive mode flag is ignored if called from outside the EDT (the UI thread). This prevents possible deadlock. (You could force interactive mode from another thread with `invokeAndWait` if you're sure it's safe.)


If you are happy with it on your end, I'll go ahead and accept the PR. I won't publish another release for a while, so if you find things don't go as smoothly as you'd like you'll have wide latitude to modify the API for a while.

**Comment by fogity** [comment]
I am happy with merging the PR.

**Comment by CGJennings** [comment]
Great. Thanks for all your work on this!

**Pull request merged**
