### PR TITLE
Expand bleed margin feature

### PR DESCRIPTION
**Pull request by fogity**
This PR expands the bleed margin functionality, including a bug fix and some quality of life improvements.

## Motivation
I was working on a component with a built in bleed margin, but found it hard/inconvenient to debug.

## Overview

* Adds a new enum `EdgeStyle` for controlling how component edges are handled;
  * `RAW`: No adjustments
  * `BLEED`: Generates a bleed margin if not included already (existing functionality)
  * `NO_BLEED`: Removes any existing bleed margin
  * `CUT`: Removes bleed and rounds the corners (see next point)
  * `HIGHLIGHT`: Traces the edge over the "raw" image (useful for debugging)
* Adds a new `getCornerRadius` method to `Sheet`, that can be used to cut off corners of the component
* Adds a new "Preview Card Edge" menu for setting the `EdgeStyle` used when previewing components
* Replaces the "Add bleed" checkbox in the export dialog with a combo box
* Adds bleed and corner support for `UndecoratedCardBack`
* Fixes bug where DIY components bleed value does not apply to plain card back
* Adds corner support for DIY components

## Preview options
It is now possible to toggle bleed and other edge styles from the "View" menu. This allows extension developers and regular users to see how the component will look with and without bleed, without the need to export images.
The selected options is stored in the user settings.
I set the default to `CUT` as that should match the physical components best.

## Export options
The "Add bleed" option will be automatically migrated to the new bleed options (`BLEED` if on, `RAW` if off).
The `HIGHLIGHT` option is not available for export.
The `CUT` option requires transparency, so will be replaced with `NO_BLEED` if the file format does not support transparency.

## Corner radius
Works just like bleed margin, but for card corners. This is just a cosmetic setting, as you wouldn't want this on when printing the components. But it is a small touch that makes the tool feel more polished (in my opinion). Requires adaption by extension authors though.

## The bug
The `UndecoratedCardBack` did not have an option to specify bleed margin. This meant that the backs of DIY components with bleed and plain back would not return the bleed margin value. This meant that when the "Add bleed" option was selected during export, the back would get and extra 9pt bleed on top of the included bleed margin.
This is fixed in this PR.

## Limitations
As I haven't used the Deck feature, I decided to skip that part in this PR. It should still work as before, but it is not possible to specify any of the new options.

### CODE REVIEW

**Comment by CGJennings** [comment]
Good stuff!

I think it might help the user to untangle these concepts a little. I'll take the blame here: bleed margins were added long after the fact, and so most designs didn't support them. Then synthetic bleed margins were added to compensate, adding to the confusion.

Setting aside rounded corners for a moment, there is really only choice of interest to the user: *do I want a bleed margin?* If the user wants a bleed margin and none exists, we should just honour their intent and silently synthesize one. (If they are not sure if they will like how it looks with a margin, they can just check the preview!) Adding in rounded corners you have three basic options:

**Bleed Margins**
1. Yes
2. No
3. No, and trim round corners

The default for previews should be (3). Since most components won't have round corners (at least to start), this will help users discover the feature once it is more widely used. The default for exports should probably be (2), since users may not understand that the card has extra material that should be trimmed off (moreover, an exported image provides no context as to where to cut.). This means the default behaviour changes for the rare card types that do include a designed margin, but that is arguably for the best. At least it will be consistent! An alternative is to add another option under "How will you use the exported images?", something like "I want images suitable for a printing service". Then *that* could default to (1).

Decks will need some minor patching up: they currently have an option to synthesize a margin if none is present. I can transition this to an option to either include a margin or not instead, eventually letting the user set an explicit margin size.

The option to add a highlight to indicate the "true" edge should be separate from whether or not the edge is rendered at all. As you pointed out, this option is more important for designing and debugging than for end users. What's more, I think you might want *more than one kind of highlight*. Specifically, sometimes you might want just the edge outline, but other times you might want to display the *safe area*. This is the area that is at least as far *inside* the card as the bleed margin:

illustration of the safe area

You may be aware that there is a "developer tools" plug-in which adds an option to show "Region Boxes", which highlights text boxes (and their `PageShape`, if any). I could see (as a separate PR) moving Region Boxes out of the developer tools plug-in and into the main app, joined by similar options like bleed margin edge, safe area, and portrait boxes.

Eventually it should perhaps be possible to request an exact bleed margin size for exports. If smaller than the built-in margin it can be trimmed, and if larger then the difference could be synthesized. This way users could meet the specific requirements of a particular print service.

In `cutCorners`, I did some tests and found that once it's warmed up this is a little faster (though it may be hardware-sensitive):

```java
        try {
            applyContextHints(g);
            g.setClip(new RoundRectangle2D.Float(0, 0, w, h, r, r));
            g.drawImage(sheetImage, null, null);
        } finally {
            g.dispose();
        }
```

I went ahead and pushed that change, though it might be even better to just set the clip before rendering the *original* image, thus avoiding the intermediate image altogether---though there would be some details to manage: a normally opaque image would have to be forced to be transparent, and it is possible that buggy painting functions might set a clip without restoring the old clip properly.

In the same vein, it *should* be possible to generate the sheet without its intended bleed margin directly, without an intermediate image, by creating a smaller bitmap of just the non-bleed area and translating the graphics context accorrdingly, similar to what is done to make the rendering scale independent.

**Comment by fogity** [comment]
Very good points!
The reason I included the `RAW` option was to maintain backwards compatibility, but if that is not a concern it is better to remove that option.

Regarding the corner cutting implementation, I first tried using the `setClip` function. But it turned out that it does not support anti-aliasing so the corner becomes jagged.

With `setClip`:
set-clip
 
With `TexturePaint`:
texture-paint

**Comment by CGJennings** [comment]
Yeah, it may be momentarily confusing for a few people, but in the long run I think it is better to drop compatibility and have a simple Yes/No option that people can wrap their heads around. Then at least the behaviour is predictable across card types. Plus it opens the door to adding support for a user-controlled width, which is even better.

Yes, you're right, it doesn't do soft clipping. In my testing the image was so large that it was scaled down in the preview and as a result it *looked* like it had soft edges! I can think of a third approach. I'll test that as well, and update with whichever version performs the best.

**Comment by CGJennings** [comment]
Did a little push to add `Sheet.setCornerRadius`. I don't see this as a problem: unlike bleed margins, corner radius doesn't require a special template image. Anyway, I needed the method! I added a simple tool to the [Developer Tools plug-in](https://github.com/CGJennings/se3-developer-tools-plugin) to interactively find the right radius.

`Sheet` will now get the radius from setting key `templateBaseKey + "-corner-radius"`, if defined. (This lets you add corner cuts without breaking the plug-in in older versions of SE.)

Once the new API for bleed margins is settled, I'll add a key for that as well, for completeness.

**Comment by CGJennings** [comment]
Would you like some help finishing this up? I think there are now more than enough changes to justify putting out an update for either late Dec 2021 or early Jan 2022. That will get the conversion features in the wild so you can go ahead with your plug-in plans, as well as some nice [script engine updates](http://se3docs.cgjennings.ca/um-release-notes.html#script-engine-updates).

**Comment by fogity** [comment]
Sorry for not responding earlier. I have been quite busy with other stuff the last few weeks, so I haven't worked any on this feature. I am not sure how much time I will have over to work on this until a bit into January. But likewise I will not have much time to work on the plug-in, so there is no hurry for a release for my sake.

I realized that I would prefer the solution where the user has the option of adjusting the bleed margin size. The main reason being that the bleed margin I have available for the plug-in is different to the standard bleed margin. So it would be good if I didn't have to worry about what bleed margin the user would expect when creating the components. It would be annoying having to process the images after exporting.

**Comment by CGJennings** [comment]
No worries! If I get a chance I'll see if I can push it forward.

**Comment by CGJennings** [comment]
Thanks for your work on this! PR merged; there are still a few small details to iron out, but it makes sense to address those separately.

**Comment by fogity** [comment]
Hi Chris,

I finally got around to checking out your changes, and it matches the
functionality I wanted, so I am very glad.

There were three things I noticed, which I thought I should mention:
- There might also be a better color than yellow to use for the card edge,
it is a bit hard to see on light backgrounds.
- The backdrop in portraits no longer gets repainted, instead the previous
content is retained (until a redraw is triggered in another way). Not sure
if it is a problem, but thought I would mention.
- And unrelated: I bought a high DPI monitor and Strange Eons does not
adapt to the UI scaling (everything is very tiny). Not sure if this is easy
or very hard to fix, but would be nice.

Thanks again for doing the rest of the work on this feature. I'll try to
test it out a bit more thoroughly soon.

Best regards,
Henrik

**Comment by fogity** [comment]
Hi again,
Just wanted to take back a comment. Seems that the UI scaling works well on
the release version, so probably just a missing flag when I run from
NetBeans.

BR,
Henrik

**Comment by CGJennings** [comment]
Yeah, yellow is a problem colour. I think it is perceived as being brighter and so the perceived contrast with white is too low. I've made it a dashed light/dark outline now, so that should help. If you like you can pull the change and let me know if it is still an issue for your specific case.

> The backdrop in portraits no longer gets repainted, instead the previous content is retained

I looked at a few designs but couldn't see what you seem to be describing. Can you give me an example with a specific component type?

High DPI support... hoo boy...

High DPI support in Java 8 for Windows is pretty messed up. Java 9 started adding true high DPI support to Swing, allowing a full-res UI without OS scaling. So, the ideal solution is moving away from Java 8. But I've been taking a cautious approach on that. Oracle has far less regard for maintaining compatibility than Sun did. There's a risk that the maintenance cost of new versions may leave the project stranded on a less-well-supported version (at the moment, it seems far more projects use Java 8 than any version that came after). But proper high DPI support is definitely one of the external pressures that are pushing for switching.

Currently, I'm planning to make the release *after* the next release be the move to a newer version of Java, most likely either 11 or 17. I've been [maintaining a branch for newer Java builds](/CGJennings/strange-eons/tree/java-9+) for a while now. The last major block to switching that I know of is that the script engine broke under Java 16+. I think this is fixed now, but haven't had time to test it thoroughly against existing plug-ins.

**Pull request merged**
