### PR TITLE
Manual conversion

### PR DESCRIPTION
**Pull request by fogity**
This is the follow up to "Component conversion", which allows the plug-in author to define manual conversion options, and allows the user to trigger manual conversion using these options in the Edit menu.

## Overview

* Adds a new conversion map file type, based on class map files, which is used to define manual conversion options
* Adds a new class `ConversionMap` for loading and looking up manual conversions.
* Adds a new "Convet to" menu in the "Edit" menu for triggering manual conversions.
* Adds a new trigger type for manual conversions.
* Adds support for the new file type to the Strange Eons code editor.

## Functionality

* Can define direct conversion options.
* Can define conversion groups, where any two members can be converted.
* Can link conversion groups so that members can be converted to any member in the other group.

The author can see which group the conversion is to, but otherwise the conversion implementation is the same.

## Notes

* I might have been a bit over-zealous with the caching. If the memory footprint becomes too large, then we might need to rethink the caching strategy.
* I am unsure about the encoding settings regarding the code editor.
* I created two wrapper classes to work around the use of colons in conversion map files, there is probably a better way to handle this.

## Example Project
[Manual Conversion Showcase.zip](https://github.com/CGJennings/strange-eons/files/7515590/Manual.Conversion.Showcase.zip)

### CODE REVIEW

**Comment by CGJennings** [comment]
It'll be a few days before I can look at this properly, but I wanted to let you know I wasn't ignoring it!

I wonder if it would sense to make this a type of factory task, given that it is for fairly advanced users already (as it requires a configuration file)? The task could have two folders (for source files and output), and the conversion config could sit in the root.

**Comment by fogity** [comment]
The configuration file is to be created by an extension author, to give conversion options to the extension users. I guess the relevance of the feature depends a lot on the game and extension setup, but I don't think the conversion options themselves are for advanced users. Here is a couple of scenarios I had in mind:

* A new edition of a game is released, it uses similar card structure, but the cards themselves are different (size, layout, etc). So you probably want a new extension. The author can then add a conversion map in the new extension, allowing the users to convert their cards if they want to.
* In e.g. Talisman there are several decks with similar types of cards. It might be nicer to split them by deck, rather than group them all together (compare Talisman2 extension with Talisman extension). But it is quite often you want the same card in multiple decks (e.g. to trigger some expansion mechanism). Currently you have to manually copy over all details, but the author could put in a conversion map with conversions between all those deck types.

The former would benefit from some bulk action, but the latter would be on a card-by-card basis. The design of the conversion map in this PR is intended to be usable by plug-ins as well (I might do a Bulk-Convert plug-in similar to Bulk-Export at some point).

The problem with the factory task is that you need to modify at least one of the component types in order to get any use of the conversion functionality. Just making a conversion map does not give you anything more than what you can already do with a script.

**Comment by CGJennings** [comment]
Ah, got it.

As far as the file encoding, your code looks correct to me. The `ResourceParser` you extend uses ISO-8859-15 unless created explicitly with an `InputStream`. Ideally it should be UTF-8, but this comes from the fact that the Java `Properties` class was originally used for this kind of thing in older versions. Sadly 8859-15 is not quite a subset of UTF-8 so it isn't possible to simply switch.

This is a bit of a tangent, but I wouldn't be against adding a constructor to `ResourceParser` to take a URL and character set name. That said, using a different encoding for conversion maps might do more harm than good since they are so similar to class maps. Anyway, conversion maps will for the most part this will contain typical "source code" characters, and for labels not covered by the encoding, there are Unicode escapes and `@` localized strings.

**Comment by CGJennings** [comment]
Hmmm... about those colons...

Allowing colons to separate keys and values is also a `java.util.Properties` thing. Anything parsed using `ca.cgjennings.io.EscapedLineReader.readProperty`, which includes `ResourceParser`, only accepts `=` as a separator. So the existing tokenizer etc. is buggy. I'll have to dig in to see if `Properties` is still used anywhere, and update those classes accordingly.

**Comment by CGJennings** [comment]
OK, I think this is ready to merge. A summary of the (minor) changes I made:
- edited the menu item label slightly to match SE conventions
- added a distinct icon for `.conversionmap` files
- renamed `getGlobalInstance` to `getShared` for consistency with other SE classes
- added a generic tokenizer/navigator for `ResourceParser` parsed files, and updated the relevant code types to use them (including conv. map)

If you are happy with how things stand, I'll go ahead and accept it.

**Comment by fogity** [comment]
Yeah, I am happy :)

**Pull request merged**
